### ISSUE TITLE
Formatting summary statistics

### ISSUE THREAD

**Issue by mkoromina** [getian107/SuSiEx#11]
Hi, 

Thank you for creating this software to run multi-ancestry SuSiE.

My question pertains to how and if summary statistics should be formatted.
Do the summary stats have to be unzipped? I also noticed that for my summary stats files, I get this error

```
Error: No sufficient tokens in summary statistics file
        "/projects/0/tmp_data/file_1_pop"
1 tokens in header.
CHR SNP BP A1 A2 FRQ_A_7076 FRQ_U_91350 INFO OR SE P ngt Direction HetISqt HetDf HetPVa Nca Nco Neff_half
snp: 2
bp: 3
a1: 4
a2: 5
eff: 9
se: 10
pval: 11
```

Let me know if more info is needed to debug this.
Many thanks!

**Comment by yorkklause** [comment]
Hi Maria,

Thank you for using our software.

The error you encountered is related to the format of your summary stats file. We require the files to be separated by "\tab" (tab) rather than spaces.
To address this issue, you can use the following command:

awk -v OFS="\t" '$1=$1' $your_sum_stat > $updated_sum_stat

This command will help convert the space-separated file to a tab-separated format and resolve the problem. Let me know if you have any further questions or issues.

My best

Kai Yuan

**Comment by mkoromina** [comment]
thanks Kai so much! 
this does solve the issue!
