### ISSUE TITLE
Build failure on Ubuntu 22.04

### ISSUE THREAD

**Issue by pettyalex** [getian107/SuSiEx#6]
Hello,

I'm unable to build SuSiEx as it exists on Github right now, it seems like there's a missing include:

```
(base) alex@alex-deskmini:~/src/SuSiEx/src$ make
g++ -c data.cpp -fopenmp
data.cpp: In member function ‘void dataset::load(const softpar&)’:
data.cpp:313:36: error: ‘isnan’ was not declared in this scope; did you mean ‘std::isnan’?
  313 |                                 if(isnan(cur.beta))
      |                                    ^~~~~
      |                                    std::isnan
In file included from data.hpp:13,
                 from data.cpp:8:
/usr/include/c++/11/cmath:632:5: note: ‘std::isnan’ declared here
  632 |     isnan(_Tp __x)
      |     ^~~~~
data.cpp:583:52: error: ‘isnan’ was not declared in this scope; did you mean ‘std::isnan’?
  583 |                                                 if(isnan(ldbuff[p]))
      |                                                    ^~~~~
      |                                                    std::isnan
In file included from data.hpp:13,
                 from data.cpp:8:
/usr/include/c++/11/cmath:632:5: note: ‘std::isnan’ declared here
  632 |     isnan(_Tp __x)
      |     ^~~~~
make: *** [makefile:8: data.o] Error 1
```

Which isnan did you mean to use? `std::isnan` or the `isnan` in `<math.h>`?

Edit: I'm dumb, those both point to the same thing in the end, of course. Either way, it's not found without changing _something_ on 22.04. Perhaps std::isnan given that this is a C++ application?

**Comment by yorkklause** [comment]
Hi pettyalex,

Thank you for downloading and utilizing our method. I noticed that I used <cmath> as the header file, which means I should use std::isnan instead of isnan. I have made the necessary code updates. Could you please use the following command to clone the repository:

git clone https://github.com/getian107/SuSiEx.git

After that, please recompile the code again. 

If you have any further questions or concerns, please don't hesitate to ask.

Kai

**Comment by pettyalex** [comment]
Thanks for the fix!
